apiVersion: apps/v1
kind: Deployment
metadata:
  name: andreasfonsterputs-wagtail
  labels:
    app: andreasfonsterputs-wagtail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andreasfonsterputs-wagtail
  template:
    metadata:
      labels:
        app: andreasfonsterputs-wagtail
    spec:
      imagePullSecrets:
        - name: regcred
      initContainers:
        - name: migrate
          image: docker.pkg.github.com/aldowntown/andreasfonsterputs/wagtail-andreasfonsterputs:v1.0.0-alpha.2
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - secretRef:
                name: secret-config
        - name: collectstatic
          image: docker.pkg.github.com/aldowntown/andreasfonsterputs/wagtail-andreasfonsterputs:v1.0.0-alpha.2
          command: ["python", "manage.py", "collectstatic", "--noinput"]
          envFrom:
            - secretRef:
                name: secret-config
      containers:
        - name: wagtail
          image: docker.pkg.github.com/aldowntown/andreasfonsterputs/wagtail-andreasfonsterputs:v1.0.0-alpha.2
          envFrom:
            - secretRef:
                name: secret-config
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: andreasfonsterputs-wagtail
spec:
  selector:
    app: andreasfonsterputs-wagtail
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: andreasfonsterputs-nextjs
  labels:
    app: andreasfonsterputs-nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: andreasfonsterputs-nextjs
  template:
    metadata:
      labels:
        app: andreasfonsterputs-nextjs
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: nextjs
          image: docker.pkg.github.com/aldowntown/andreasfonsterputs/nextjs-andreasfonsterputs:v1.0.0-alpha.2
          envFrom:
            - secretRef:
                name: secret-config
          env:
            - name: GRANIT_WAGTAIL_API_URL
              value: http://andreasfonsterputs-wagtail.andreasfonsterputs-production.svc.cluster.local/api/wagtail/v2/
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: andreasfonsterputs-nextjs
spec:
  selector:
    app: andreasfonsterputs-nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: andreasfonsterputs
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-issuer
spec:
  tls:
    - hosts:
        - andreasfonsterputs.mygranit.site
      secretName: tls-proxied-self-signed
  rules:
    - host: andreasfonsterputs.mygranit.site
      http:
        paths:
          - path: /admin
            backend:
              serviceName: andreasfonsterputs-wagtail
              servicePort: 80
          - path: /api/preview
            backend:
              serviceName: andreasfonsterputs-nextjs
              servicePort: 80
          - path: /api
            backend:
              serviceName: andreasfonsterputs-wagtail
              servicePort: 80
          - path: /
            backend:
              serviceName: andreasfonsterputs-nextjs
              servicePort: 80
