# Generated by Django 3.1.5 on 2021-01-26 10:08

from django.db import migrations


def forward(apps, schema_editor):
    Locale = apps.get_model("wagtailcore", "Locale")
    db_alias = schema_editor.connection.alias
    Locale.objects.using(db_alias).filter(language_code="en").update(language_code="sv")


def backward(apps, schema_editor):
    Locale = apps.get_model("wagtailcore", "Locale")
    db_alias = schema_editor.connection.alias
    Locale.objects.using(db_alias).filter(language_code="sv").update(language_code="en")


class Migration(migrations.Migration):

    dependencies = [
        ("hemforbattringen", "0002_auto_20210126_0441"),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
