# Generated by Django 3.1.5 on 2021-02-15 06:55

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailgranit.blocks
import wagtailgranit.contrib.forms.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('hemforbattringen', '0005_auto_20210214_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='economy_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='page_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('background_video', wagtailgranit.blocks.MediaChooserBlock(required=False)), ('overline', wagtail.core.blocks.CharBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('to', wagtailgranit.blocks.PageOrLinkChooserBlock(required=False))]))])), ('image_and_content', wagtail.core.blocks.StructBlock([('image_placement', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('image', wagtail.core.blocks.StructBlock([('image', wagtailgranit.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.TextBlock(required=False))])), ('heading', wagtail.core.blocks.CharBlock()), ('preamble', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('to', wagtailgranit.blocks.PageOrLinkChooserBlock(required=False))], required=False))])), ('customer_segments', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('background_video', wagtailgranit.blocks.MediaChooserBlock(required=False)), ('intro', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])), ('segments', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('icon', wagtailgranit.blocks.IllustrationChooserBlock()), ('name', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('price', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('to', wagtailgranit.blocks.PageOrLinkChooserBlock(required=False))]))]), max=3))])), ('usp', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtailgranit.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.TextBlock(required=False))])), ('logo', wagtailgranit.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.TextBlock()), ('usps', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])))])), ('callout', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(required=False)), ('to', wagtailgranit.blocks.PageOrLinkChooserBlock(required=False))]))])), ('features', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('heading', wagtail.core.blocks.CharBlock(required=False)), ('text', wagtail.core.blocks.TextBlock(required=False)), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock())])))])), ('partners', wagtail.core.blocks.StructBlock([('partner_logos', wagtail.core.blocks.ListBlock(wagtailgranit.blocks.ImageChooserBlock())), ('text', wagtail.core.blocks.TextBlock())])), ('product_categories', wagtail.core.blocks.StructBlock([('categories', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('link', wagtailgranit.blocks.PageChooserBlock(return_html_url=True)), ('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('icon', wagtailgranit.blocks.IllustrationChooserBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])))])), ('text_on_image', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('background_video', wagtailgranit.blocks.MediaChooserBlock(required=False)), ('heading', wagtail.core.blocks.CharBlock(required=False)), ('text', wagtail.core.blocks.CharBlock(required=False))])), ('form', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtailgranit.blocks.ImageChooserBlock(required=False)), ('caption', wagtail.core.blocks.TextBlock(required=False))])), ('secondary', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('preamble', wagtail.core.blocks.TextBlock(required=False)), ('text', wagtail.core.blocks.TextBlock(required=False))])), ('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.CharBlock()), ('form', wagtailgranit.contrib.forms.blocks.FormChooserBlock())])), ('video', wagtail.core.blocks.StructBlock([('video', wagtailgranit.blocks.MediaChooserBlock()), ('auto_play', wagtail.core.blocks.BooleanBlock(required=False)), ('loop', wagtail.core.blocks.BooleanBlock(required=False)), ('controls', wagtail.core.blocks.BooleanBlock(required=False))]))], verbose_name='Body'),
        ),
    ]
