# Generated by Django 3.1.5 on 2021-01-26 04:41

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtailgranit.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('andreasfonsterputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='page_header_brightness',
            field=models.CharField(choices=[('dark', 'Dark'), ('bright', 'Bright')], default='dark', max_length=6),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('overline', wagtail.core.blocks.CharBlock()), ('heading', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('to', wagtailgranit.blocks.PageChooserBlock(return_html_url=True))]))])), ('image_and_content', wagtail.core.blocks.StructBlock([('image_placement', wagtail.core.blocks.ChoiceBlock(choices=[('left', 'Left'), ('right', 'Right')])), ('image', wagtail.core.blocks.StructBlock([('image', wagtailgranit.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.TextBlock(required=False))])), ('heading', wagtail.core.blocks.CharBlock()), ('preamble', wagtail.core.blocks.TextBlock()), ('body', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('to', wagtailgranit.blocks.PageChooserBlock(return_html_url=True))]))])), ('customer_segments', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('intro', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])), ('segments', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('price', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('to', wagtailgranit.blocks.PageChooserBlock(return_html_url=True))]))]), max=3))])), ('usp', wagtail.core.blocks.StructBlock([('image', wagtail.core.blocks.StructBlock([('image', wagtailgranit.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.TextBlock(required=False))])), ('logo', wagtailgranit.blocks.ImageChooserBlock()), ('text', wagtail.core.blocks.TextBlock()), ('usps', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock())])))])), ('callout', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.TextBlock()), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock()), ('to', wagtailgranit.blocks.PageChooserBlock(return_html_url=True))]))])), ('features', wagtail.core.blocks.StructBlock([('background_image', wagtailgranit.blocks.ImageChooserBlock()), ('features', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock()), ('description', wagtail.core.blocks.CharBlock())])))]))]),
        ),
    ]
