# Generated by Django 3.1.7 on 2021-03-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailgranit', '0002_auto_20210311_1056'),
        ('andreasfonsterputs', '0008_auto_20210216_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='logo_bright',
            field=models.ForeignKey(blank=True, help_text='The logo that is displayed when the page header brightness is set to bright', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailgranit.illustration', verbose_name='Logo bright'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_dark',
            field=models.ForeignKey(blank=True, help_text='The logo that is displayed when the page header brightness is set to dark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailgranit.illustration', verbose_name='Logo dark'),
        ),
    ]
